// This file is generated automatically by Next.js
// Do not edit this file manually

export type AppRoutes = "/" | "/counter"

export type LayoutRoutes = "/"

export type ParamMap = {
  "/": Record<string, never>
  "/counter": { id?: string }
}
